name: projjoblink
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.6
  riverpod: ^2.0.0
  flutter_riverpod: ^2.0.0
  uuid: ^3.0.4
  crypto: ^3.0.3
  sqflite_common_ffi: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
